apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: instance-manager-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: instance-manager-clusterrole
  apiGroup: rbac.authorization.k8s.io
