# Use an official Python runtime as a base image
FROM python:3.8-slim

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install Gunicorn
RUN pip install gunicorn

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define environment variable to improve Flask performance
ENV FLASK_ENV=production

# Run app.py using Gunicorn, bind to 0.0.0.0:8000
CMD ["gunicorn", "-b", "0.0.0.0:8000", "app:app"]
