# docker buildx build --platform linux/amd64,linux/arm64 -t gcr.io/edurangectf/instance-manager . --push

FROM python:3.8-slim

# Install dependencies
RUN apt-get update && apt-get install -y \
    libffi-dev \
    libssl-dev \
    gcc \
    libc-dev \
    make \
    curl \
    && apt-get clean



# Copy application files
COPY requirements.txt /app/requirements.txt

# Install Python packages
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the application code
COPY . /app

WORKDIR /app

# Run the application
CMD ["gunicorn", "-b", "0.0.0.0:8000", "app:app", "--worker-class", "eventlet", "--workers", "1"]
