apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instance-manager-clusterrole
rules:
- apiGroups: [""]
  resources: ["services", "pods", "pods/portforward", "secrets"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: ["networking.gke.io"]
  resources: ["loadbalancers"]
  verbs: ["get", "list", "create", "delete", "update"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
- apiGroups: ["autoscaling.k8s.io"]
  resources: ["verticalpodautoscalers"]
  verbs: ["get", "list", "create", "delete", "update"]
