apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-hba-conf
data:
  pg_hba.conf: |
    # PostgreSQL Client Authentication Configuration File

    host    all             all             0.0.0.0/0               md5
    
