apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-clusterissuer
spec:
  acme:
    email: ryderselikow@lclark.edu
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: ryderselikow@lclark.edu
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
