apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate-prod
  namespace: default
spec:
  secretName: wildcard-domain-certificate-prod
  issuerRef:
    name: cert-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - '*.edurange.cloud'
  - 'edurange.cloud'
