---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terminal-account
  namespace: default
  annotations:
    kubernetes.io/service-account.name: "terminal-account"
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: terminal-exec-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: terminal-exec-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: terminal-account
    namespace: default
roleRef:
  kind: Role
  name: terminal-exec-role
  apiGroup: rbac.authorization.k8s.io 