apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docker-registry-prod
spec:
  secretName: letsencrypt-secret-prod
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - registry.rydersel.cloud

