apiVersion: batch/v1
kind: CronJob
metadata:
  name: registry-garbage-collector
spec:
  schedule: "0 */6 * * *"  # Run every 6 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: registry-gc
              image: registry:2
              args:
                - /bin/registry
                - garbage-collect
                - --delete-untagged
                - /etc/docker/registry/config.yml
              volumeMounts:
                - name: registry-storage
                  mountPath: /var/lib/registry
                - name: registry-config
                  mountPath: /etc/docker/registry/config.yml
                  subPath: config.yml
          volumes:
            - name: registry-storage
              persistentVolumeClaim:
                claimName: registry-pvc
            - name: registry-config
              configMap:
                name: registry-config
          restartPolicy: OnFailure
