apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: harbor-core-hpa
  namespace: harbor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: harbor-core
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: harbor-registry-hpa
  namespace: harbor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: harbor-registry
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: harbor-jobservice-hpa
  namespace: harbor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: harbor-jobservice
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: harbor-portal-hpa
  namespace: harbor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: harbor-portal
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: harbor-trivy-hpa
  namespace: harbor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: harbor-trivy
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 