# Use a lightweight Linux base image
FROM debian:buster-slim

# Install necessary tools
RUN apt-get update && \
    apt-get install -y vim less openssl && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /challenge

# Copy the challenge scripts
COPY challenge/generate_challenge.sh .
COPY check_solution.sh /usr/local/bin/check_solution
COPY entrypoint.sh /entrypoint.sh

# Make scripts executable
RUN chmod +x /entrypoint.sh /usr/local/bin/check_solution generate_challenge.sh

# Set the entrypoint script to run on container start
ENTRYPOINT ["/entrypoint.sh"]
