apiVersion: v1
kind: Pod
metadata:
  name: challenge-pod
  labels:
    app: challenge
spec:
  serviceAccountName: terminal-account  # Ensure the correct service account is used
  containers:
  - name: challenge-container
    image: registry.rydersel.cloud/debiantest   # Gets overwritten anyway
    ports:
    - containerPort: 22
      name: ssh
    securityContext:
      runAsUser: 0  # Run as root user
      privileged: false
    env:
    - name: FLAG
      value: "flag"
  - name: webos
    image: registry.rydersel.cloud/webos
    imagePullPolicy: Always
    ports:
    - containerPort: 3000
      name: webos-http
    env:
    - name: NEXT_PUBLIC_POD_NAME
      value: "$(POD_NAME)"
    - name: NEXT_PUBLIC_APPS_CONFIG
      value: "$(NEXT_PUBLIC_APPS_CONFIG)"
    - name: NEXT_PUBLIC_CHALLENGE_POD_NAME
      value: "$(POD_NAME)"
    - name: NEXT_PUBLIC_CHALLENGE_API_URL
      value: "http://localhost:5000/execute"
    - name: NEXT_PUBLIC_TERMINAL_URL
      value: "https://terminal-$(POD_NAME).$(INGRESS_URL)"
    - name: NEXT_PUBLIC_CHALLENGE_URL
      value: "https://$(POD_NAME).$(INGRESS_URL)"
    - name: DATABASE_API_URL
      value: "http://database-api-service.default.svc.cluster.local"
    - name: INSTANCE_MANAGER_URL
      value: "http://instance-manager.default.svc.cluster.local/api"
  - name: terminal
    image: registry.rydersel.cloud/terminal
    imagePullPolicy: Always
    ports:
    - containerPort: 3001
      name: terminal-http
    env:
    - name: KUBERNETES_HOST
      value: "b5c39586-ba37-4e81-8e40-910d6880ff14.us-ord-1.linodelke.net:443"
    - name: KUBERNETES_NAMESPACE
      value: "default"
    - name: KUBERNETES_SERVICE_ACCOUNT_TOKEN  # 我不喜欢你
      value: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjRNOU1rRFh3SlVVb1FGLWpJX3BobjZJMkFkYUhNdHZFRmdzUGJPRDV1ZzQifQ.eyJhdWQiOlsia3ViZXJuZXRlcy5kZWZhdWx0LnN2YyJdLCJleHAiOjE3NTY4MzQ1ODEsImlhdCI6MTcyMDgzODE4MSwiaXNzIjoiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJqdGkiOiI5NmY4N2E4My1iZjNhLTQyOWItYTVkMy03YjNkNTQ5MDIyNWUiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6ImRlZmF1bHQiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoidGVybWluYWwtYWNjb3VudCIsInVpZCI6IjE2OTcyN2JmLTUyNGEtNGE1Zi1hMWNlLTJiNTgxNTFjMGY4YiJ9fSwibmJmIjoxNzIwODM4MTgxLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDp0ZXJtaW5hbC1hY2NvdW50In0.uukNAgl0b6lGbFNBy3ak6XRf5NiviHnvQf0xV2Vbs_vh57GMvzy1L7ZY2-KIQKQar5YeaYp8lfnzsF_bRS6315c_8cTWMuxZdnECd7GfSCyQYph1gZrz_oXMqB16891d5dHSVrdXKiYN4-916ddxNSPExZzwQ-MUPKw5KRHgFMF3R2uofVnhwxLaDzbVsmwnNx4y0QTJNKstVc4eWJdhdJ2QDOC0uW8vnoCJob4IthXWxqkBdf1Z63pNH4BcrM9N3hix_ltOnw1wla_OAHxPnY0w6MHHtZWzOolboFUU6SvJHSfeZQRQIR8keAJAuJWl1VAwXoDXrKZ59dluKLDIqA"
    - name: POD_NAME
      value: "alpine-deployment-7fccf844b5-drwr5"
    - name: CONTAINER_NAME
      value: "challenge-container"
---
apiVersion: v1
kind: Service
metadata:
  name: challenge-service
spec:
  selector:
    app: challenge
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    name: webos-http
  - protocol: TCP
    port: 3001
    targetPort: 3001
    name: terminal-http
  type: ClusterIP  # Changed to ClusterIP for internal routing
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: challenge-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    # WebSocket support annotations
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/websocket-services: "challenge-service"
  #  cert-manager.io/cluster-issuer: "cert-clusterissuer"  # Use the correct cluster issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - instance-name.rydersel.cloud
    - terminal-instance-name.rydersel.cloud
    secretName: wildcard-domain-certificate-prod
  rules:
  - host: instance-name.rydersel.cloud
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: challenge-service
            port:
              number: 80
  - host: terminal-instance-name.rydersel.cloud
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: challenge-service
            port:
              number: 3001
