apiVersion: v1
kind: Pod
metadata:
  name: challenge-pod
  labels:
    app: challenge
spec:
  containers:
  - name: webos
    image: gcr.io/edurangectf/webos
    ports:
    - containerPort: 3000
      name: http
  - name: bridge
    image: gcr.io/edurangectf/bridge:latest
    ports:
      - containerPort: 5000
        name: http
    env:
      - name: WEB_CHAL_LINK
        value: "none"

---
apiVersion: v1
kind: Service
metadata:
  name: challenge-service
spec:
  selector:
    app: challenge
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000  # Expose the WebOS container
  type: ClusterIP  # Changed to ClusterIP for internal routing
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: challenge-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: challenge.rydersel.cloud  # This will be replaced dynamically
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: challenge-service
            port:
              number: 80
