#!/bin/bash

echo "====================================================================="
echo "                METASPLOIT PROOF OF CONCEPT CHALLENGE                "
echo "====================================================================="
echo ""
echo "Welcome to the Metasploit Connection Challenge!"
echo ""
echo "In this simple proof of concept, you will use Metasploit to connect"
echo "to a shell already running on the defense container, then locate the"
echo "hidden flag file."
echo ""
echo "TARGET: The netcat listener is running at ${DEFENSE_CONTAINER_HOST:-localhost}:4444"
echo ""

# Check user and directory permissions
echo "System Information:"
echo " - User: $(whoami)"
echo " - Home directory: $HOME"
echo " - Working directory: $(pwd)"
echo ""

echo "SUGGESTED APPROACH:"
echo ""
echo "1. Using the helper script (RECOMMENDED):"
echo "   $ python3 /home/kali/exploit.py"
echo "   This script provides multiple connection methods with proper handling."
echo ""
echo "2. Manual Metasploit usage:"
echo "   $ msfconsole"
echo "   msf> use auxiliary/scanner/socket/tcp_connect"
echo "   msf> set RHOSTS ${DEFENSE_CONTAINER_HOST:-localhost}"
echo "   msf> set RPORT 4444"
echo "   msf> run"
echo "   # After confirming connectivity, exit and use netcat"
echo "   msf> exit"
echo "   $ nc ${DEFENSE_CONTAINER_HOST:-localhost} 4444"
echo ""
echo "3. Direct connection with netcat:"
echo "   $ nc ${DEFENSE_CONTAINER_HOST:-localhost} 4444"
echo ""
echo "GOAL: Find the hidden flag file somewhere in the defense container's filesystem."
echo "HINT: Look for files with the flag text/pattern"
echo ""
echo "COMMON COMMANDS TO TRY:"
echo " - find / -name \"*flag*\" 2>/dev/null"
echo " - cat /home/user/flag.txt   (most likely location)"
echo " - grep -r \"CTF\" /home /var /etc 2>/dev/null"
echo ""
echo "====================================================================="
echo ""

sleep infinity

