apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-controller
  labels:
    app: database-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-controller
  template:
    metadata:
      labels:
        app: database-controller
    spec:
      containers:
      - name: database-api
        image: ${REGISTRY_URL}/database-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: postgres-host
        - name: POSTGRES_NAME
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: postgres-name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: postgres-password
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: database-url
      - name: database-sync
        image: ${REGISTRY_URL}/database-sync:latest
        imagePullPolicy: Always
        env:
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: postgres-host
        - name: POSTGRES_NAME
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: postgres-name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: postgres-password
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: database-url
        - name: INSTANCE_MANAGER_URL
          value: "http://instance-manager.default.svc.cluster.local/api"

---

apiVersion: v1
kind: Service
metadata:
  name: database-api-service
  labels:
    app: database-controller
spec:
  selector:
    app: database-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
