FROM python:3.10-slim


WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

RUN prisma generate --generator client_py

# Copy the .env file
COPY .env .env

# Run sync.py when the container launches
CMD ["python", "sync.py"]
